#!/usr/bin/env python3
"""Publish the hand-eye calibration result as static TF (plan step 5).

Reads the YAML written by solve_handeye.py (Dv-Rosws scripts) and runs
`ros2 run tf2_ros static_transform_publisher` for `base -> camera_optical`
(and optionally `tool0 -> screen_center`). Frames are taken from the YAML
itself; remember the stack distinguishes `base` (UR convention, used here)
from `base_link` (REP-103/MoveIt) — see docs/Robot_Control/ur3e_robot_control_architecture.md.

Usage:
    scripts/publish_camera_tf.py calibration/handeye_result.yaml
    scripts/publish_camera_tf.py result.yaml --with-mire
    scripts/publish_camera_tf.py result.yaml --print-only
    scripts/publish_camera_tf.py result.yaml --write-xacro camera_calibration.xacro
"""

from __future__ import annotations

import argparse
import math
import shlex
import subprocess
import sys
from pathlib import Path

import yaml

REQUIRED_KEYS = ("parent", "child", "xyz", "quat_xyzw")


def load_transform(data: dict, key: str) -> dict:
    transform = data.get(key)
    if not isinstance(transform, dict):
        raise ValueError(f"missing {key} block in the result YAML")
    for required in REQUIRED_KEYS:
        if required not in transform:
            raise ValueError(f"{key} is missing '{required}'")
    if len(transform["xyz"]) != 3 or len(transform["quat_xyzw"]) != 4:
        raise ValueError(f"{key} must have xyz[3] and quat_xyzw[4]")
    norm = math.sqrt(sum(float(v) ** 2 for v in transform["quat_xyzw"]))
    if abs(norm - 1.0) > 1e-6:
        raise ValueError(f"{key} quaternion is not normalized (|q| = {norm})")
    return transform


def publisher_command(transform: dict, child_override: str | None = None) -> list[str]:
    x, y, z = (str(float(v)) for v in transform["xyz"])
    qx, qy, qz, qw = (str(float(v)) for v in transform["quat_xyzw"])
    child = child_override or str(transform["child"])
    return [
        "ros2", "run", "tf2_ros", "static_transform_publisher",
        "--x", x, "--y", y, "--z", z,
        "--qx", qx, "--qy", qy, "--qz", qz, "--qw", qw,
        "--frame-id", str(transform["parent"]),
        "--child-frame-id", child,
    ]


def xacro_text(transforms: list[dict]) -> str:
    """Fixed-joint URDF fragment, the section-5 alternative result format."""
    lines = [
        '<?xml version="1.0"?>',
        '<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="handeye_calibration">',
        "  <!-- Generated by scripts/publish_camera_tf.py from the hand-eye result. -->",
    ]
    for transform in transforms:
        parent = transform["parent"]
        child = transform["child"]
        x, y, z = (float(v) for v in transform["xyz"])
        roll, pitch, yaw = (float(v) for v in transform["rpy_rad"])
        lines += [
            f'  <link name="{child}"/>',
            f'  <joint name="{parent}_to_{child}" type="fixed">',
            f'    <parent link="{parent}"/>',
            f'    <child link="{child}"/>',
            f'    <origin xyz="{x:.9f} {y:.9f} {z:.9f}" rpy="{roll:.9f} {pitch:.9f} {yaw:.9f}"/>',
            "  </joint>",
        ]
    lines.append("</robot>")
    return "\n".join(lines) + "\n"


def parse_args(argv=None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("result_yaml", help="YAML written by solve_handeye.py --output-yaml")
    parser.add_argument(
        "--child-frame",
        help="Override the camera child frame name (default: the YAML value, "
        "e.g. publish camera_optical_frame instead of camera_optical)",
    )
    parser.add_argument(
        "--with-mire",
        action="store_true",
        help="Also publish tool0 -> screen_center from T_tool0_mire",
    )
    parser.add_argument(
        "--print-only",
        action="store_true",
        help="Print the publisher command lines without running them",
    )
    parser.add_argument(
        "--write-xacro",
        metavar="PATH",
        help="Write a fixed-joint URDF/xacro fragment for the transforms and exit",
    )
    return parser.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)
    path = Path(args.result_yaml)
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        print(f"error: cannot read {path}: {exc}", file=sys.stderr)
        return 2

    try:
        transforms = [load_transform(data, "T_base_camera")]
        if args.with_mire or args.write_xacro:
            transforms.append(load_transform(data, "T_tool0_mire"))
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    if args.write_xacro:
        out = Path(args.write_xacro)
        out.write_text(xacro_text(transforms), encoding="utf-8")
        print(f"xacro fragment: {out}")
        return 0

    commands = [publisher_command(transforms[0], args.child_frame)]
    if args.with_mire:
        commands.append(publisher_command(transforms[1]))

    for command in commands:
        print(" ".join(shlex.quote(part) for part in command))
    if args.print_only:
        return 0

    processes = [subprocess.Popen(command) for command in commands]
    try:
        for process in processes:
            process.wait()
    except KeyboardInterrupt:
        for process in processes:
            process.terminate()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
