#!/usr/bin/env python3
"""Refresh docs/Agent_Wiki/Inventory.md from repository metadata."""

from __future__ import annotations

import pathlib
import xml.etree.ElementTree as ET


ROOT = pathlib.Path(__file__).resolve().parents[1]
WIKI_INVENTORY = ROOT / "docs" / "Agent_Wiki" / "Inventory.md"


def clean_text(value: str | None) -> str:
    if not value:
        return ""
    return " ".join(value.split())


def package_rows() -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for package_xml in sorted((ROOT / "src").glob("*/package.xml")):
        try:
            root = ET.parse(package_xml).getroot()
        except ET.ParseError:
            continue
        name = clean_text(root.findtext("name")) or package_xml.parent.name
        description = clean_text(root.findtext("description")) or "No description."
        rel = package_xml.parent.relative_to(ROOT).as_posix()
        rows.append((name, rel, description))
    return rows


def markdown_docs() -> list[str]:
    ignored_parts = {
        ".git",
        "build",
        "install",
        "log",
        ".deps",
        ".venv",
        ".pytest_cache",
        "__pycache__",
    }
    ignored_prefixes = ("docs/Agent_Wiki/", "wiki/")
    docs: list[str] = []
    for path in ROOT.rglob("*.md"):
        rel = path.relative_to(ROOT).as_posix()
        parts = set(path.relative_to(ROOT).parts)
        if rel == "AGENTS.md" or rel == "CLAUDE.md":
            continue
        if rel.startswith(ignored_prefixes):
            continue
        if parts & ignored_parts:
            continue
        docs.append(rel)
    return sorted(docs)


def markdown_title(rel_path: str) -> str:
    path = ROOT / rel_path
    try:
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            stripped = line.strip()
            if stripped.startswith("# "):
                return stripped[2:].strip()
    except OSError:
        pass
    return pathlib.Path(rel_path).name


def render() -> str:
    package_lines = [
        f"- `{name}` (`{rel}`): {description}"
        for name, rel, description in package_rows()
    ]
    doc_lines = [f"- `{doc}`: {markdown_title(doc)}" for doc in markdown_docs()]
    lines = [
        "# Inventory",
        "",
        "Generated by `scripts/update_agent_wiki.py`.",
        "",
        "## ROS Packages",
        "",
        *(package_lines or ["- None found."]),
        "",
        "## Markdown Docs",
        "",
        *(doc_lines or ["- None found."]),
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    WIKI_INVENTORY.write_text(render(), encoding="utf-8")


if __name__ == "__main__":
    main()
